#### general settings
name: UM_IDDM_SM_IB
#use_tb_logger: true
model: learnableFD

gpu_ids: [0, 1]

file_to_be_store:
  - './Configurations/config.yml'
  - './models/drift_noise_model.py'
  - './models/SDEs/driftSDE.py'
  - './data/MedSpeckle.py'
  - './models/modules/MSM_degEmb_Unet.py'

artifact_type: ['speckle in OCT', 'speckle in ultra sound', 'noise in cryo-EM image', 'noise in low dose CT', 'Gaussian noise in MRI']
type_map_ind:
  speckle in OCT: 0
  speckle in ultra sound: 1
  noise in cryo-EM image: 2
  noise in low dose CT: 3
  Gaussian noise in MRI: 4

degradation: # for some synthetic dataset that only have GTs
  # for denoising
  sigma: 25
  noise_type: G # Gaussian noise: G
  # for super-resolution
  scale: 4

#### datasets
datasets:
  train:
    name: train_dataset
    mode: SpeckleMed
    max_dataset_size: 8
    batch_size: 4
    n_workers: 0
    dataset_file: dataset/dataset_file.json
    dataset_file_win: dataset/dataset_file.json
    use_artifact_type: ['speckle in OCT', 'speckle in ultra sound', 'noise in cryo-EM image', 'noise in low dose CT', 'Gaussian noise in MRI']
  val:
    name: val_dataset
    mode: SpeckleMed
    max_dataset_size: 1
    batch_size: 1
    n_workers: 0
    dataset_file: dataset/dataset_file.json
    dataset_file_win: dataset/dataset_file.json
    use_artifact_type: ['speckle in OCT', 'speckle in ultra sound', 'noise in cryo-EM image', 'noise in low dose CT', 'Gaussian noise in MRI']

#### network structures
network_G:
  which_model_G: ConditionalUNet
  setting:
    in_nc: 1
    out_nc: 1
    nf: 64
    ch_mult: [1, 2, 4, 4]
    context_dim: 512
    use_degra_context: False
    use_image_context: False

#### path
path:
  pretrain_model_G: ~
  ema_resumed: ~
  strict_load: true
  resume_state: ~
  daclip: pretrained/ViT-B-32.pt


#### training settings: learning rate scheme, loss
train:
  dist: True
  which_sde: driftSDE
  which_model: DriftNoise
  nepoch: 500

  warmup_iter: -1  # no warm up
  lr_steps: [200000, 400000, 600000]
  lr_gamma: 0.5

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0
  val_freq: 3 #!!float 1e4

#### logger
logger:
  print_freq: 200
  save_checkpoint_freq: 8 #!!float 1e4

optimization:
  nepoch: 250



#### models
models:
  DriftNoise:
    module_name: drift_noise_model
    class_name: CLIPDriftModel
    nnet_settings:
      module_name: MSM_degEmb_Unet
      class_name: LearnableForwardUNet_MultiScoreMap
      in_nc: 2
      out_nc: 5
      nf: 64
      ch_mult: [1, 2, 4, 4]
      context_dim: 512
      text_module: scoremap
      score_map_chan: 16
      if_MultiScoreMap: True
      score_map_ch_mult: [ 1, 1, 2, 4 ]
      score_map_ngf: 16
    dnet_settings:
      module_name: MSM_degEmb_Unet
      class_name: LearnableForwardUNet_MultiScoreMap
      in_nc: 2
      out_nc: 5
      nf: 64
      ch_mult: [1, 2, 4, 4]
      context_dim: 512
      text_module: scoremap
      score_map_chan: 16
      if_MultiScoreMap: True
      score_map_ch_mult: [1, 1, 2, 4]
      score_map_ngf: 16
    use_image_context: True
    use_degra_context: False
    if_MultiScoreMap: True
    score_map_ch_mult: [1, 1, 2, 4 ]
    score_map_ngf: 64
    text_encoder_pretrain_path: pretrained/ViT-B-32.pt
    drift_net_lr: !!float 2e-5
    noise_net_lr: !!float 2e-5
    weight_decay_drift: !!float 1e-4
    eta_min: !!float 1e-6
    beta1: 0.9
    beta2: 0.99
    optimize_target: std
    optimize_type: inputRes
    drift_loss: l2
    noise_loss: none

  DDPM:
    module_name: ddpm_model
    class_name: CLIPDDPMModel
    net_settings:
      module_name: LearnableFDUnet
      class_name: LearnableForwardUNet
      in_nc: 2
      out_nc: 5
      nf: 64
      ch_mult: [1, 2, 4, 4]
      context_dim: 512
      text_module: scoremap
      score_map_chan: 16
    text_encoder_pretrain_path: pretrained/ViT-B-32.pt
    noise_net_lr: !!float 2e-5
    weight_decay: !!float 1e-4
    eta_min: !!float 1e-6
    beta1: 0.9
    beta2: 0.99

sdes:
  driftSDE:
    class_name: driftSDE
    T: 100
    max_sigma: 0.4
    drift_schedule: sigmoid
    noise_schedule: sigmoid
  ddpm:
    class_name: DDPM
    max_sigma: 1
    T: 100
    schedule: cosine_alpha
